-- colorscheme
-- define color palette
local p = {
  black = '#1C1C1C',
  white = '#EFF0EB',
}

-- loop through table and highlight all groups
local function apply_highlights(hi_table)
  vim.api.nvim_command('highlight clear')
  vim.opt.background = 'dark'
  vim.opt.termguicolors = true

  for group, styles in pairs(hi_table) do
    vim.api.nvim_set_hl(0, group, styles)
  end
end

-- define highlight-groups
local highlight_groups_table = {
  ColorColumn = { fg = p.white, bg = p.black },
  Conceal = { fg = p.white, bg = p.black },
  Cursor = { fg = p.white, bg = p.black },
  lCursor = { fg = p.white, bg = p.black },
  CursorIM = { fg = p.white, bg = p.black },
  CursorColumn = { fg = p.white, bg = p.black },
  CursorLine = { fg = p.white, bg = p.black },
  Directory = { fg = p.white, bg = p.black },
  DiffAdd = { fg = p.white, bg = p.black },
  DiffChange = { fg = p.white, bg = p.black },
  DiffDelete = { fg = p.white, bg = p.black },
  DiffText = { fg = p.white, bg = p.black },
  EndOfBuffer = { fg = p.white, bg = p.black },
  TermCursor = { fg = p.white, bg = p.black },
  TermCursorNC = { fg = p.white, bg = p.black },
  ErrorMsg = { fg = p.white, bg = p.black },
  WinSeparator = { fg = p.white, bg = p.black },
  Folded = { fg = p.white, bg = p.black },
  FoldColumn = { fg = p.white, bg = p.black },
  SignColumn = { fg = p.white, bg = p.black },
  IncSearch = { fg = p.white, bg = p.black },
  Substitute = { fg = p.white, bg = p.black },
  LineNr = { fg = p.white, bg = p.black },
  LineNrAbove = { fg = p.white, bg = p.black },
  LineNrBelow = { fg = p.white, bg = p.black },
  CursorLineNr = { fg = p.white, bg = p.black },
  CursorLineSign = { fg = p.white, bg = p.black },
  CursorLineFold = { fg = p.white, bg = p.black },
  MatchParen = { fg = p.white, bg = p.black },
  ModeMsg = { fg = p.white, bg = p.black },
  MsgArea = { fg = p.white, bg = p.black },
  MsgSeparator = { fg = p.white, bg = p.black },
  MoreMsg = { fg = p.white, bg = p.black },
  NonText = { fg = p.white, bg = p.black },
  Normal = { fg = p.white, bg = p.black },
  NormalFloat = { fg = p.white, bg = p.black },
  NormalNC = { fg = p.white, bg = p.black },
  Pmenu = { fg = p.white, bg = p.black },
  PmenuSel = { fg = p.white, bg = p.black },
  PmenuSbar = { fg = p.white, bg = p.black },
  PmenuThumb = { fg = p.white, bg = p.black },
  Question = { fg = p.white, bg = p.black },
  QuickFixLinendow = { fg = p.white, bg = p.black },
  Search = { fg = p.white, bg = p.black },
  SpecialKey = { fg = p.white, bg = p.black },
  SpellBad = { fg = p.white, bg = p.black },
  SpellCap = { fg = p.white, bg = p.black },
  SpellLocal = { fg = p.white, bg = p.black },
  SpellRare = { fg = p.white, bg = p.black },
  StatusLine = { fg = p.white, bg = p.black },
  StatusLineNC = { fg = p.white, bg = p.black },
  TabLine = { fg = p.white, bg = p.black },
  TabLineFill = { fg = p.white, bg = p.black },
  TabLineSel = { fg = p.white, bg = p.black },
  Title = { fg = p.white, bg = p.black },
  Visual = { fg = p.white, bg = p.black },
  VisualNOS = { fg = p.white, bg = p.black },
  WarningMsg = { fg = p.white, bg = p.black },
  whitespace = { fg = p.white, bg = p.black },
  WildMenu = { fg = p.white, bg = p.black },

  TSAttribute = { fg = p.white, bg = p.black },
  TSBoolean = { fg = p.white, bg = p.black },
  TSCharacter = { fg = p.white, bg = p.black },
  TSComment = { fg = p.white, bg = p.black },
  TSConditional = { fg = p.white, bg = p.black },
  TSConstant = { fg = p.white, bg = p.black },
  TSConstBuiltin = { fg = p.white, bg = p.black },
  TSConstMacro = { fg = p.white, bg = p.black },
  TSConstructor = { fg = p.white, bg = p.black },
  TSError = { fg = p.white, bg = p.black },
  TSException = { fg = p.white, bg = p.black },
  TSField = { fg = p.white, bg = p.black },
  TSFloat = { fg = p.white, bg = p.black },
  TSFunction = { fg = p.white, bg = p.black },
  TSFuncBuiltin = { fg = p.white, bg = p.black },
  TSFuncMacro = { fg = p.white, bg = p.black },
  TSInclude = { fg = p.white, bg = p.black },
  TSKeyword = { fg = p.white, bg = p.black },
  TSKeywordFunction = { fg = p.white, bg = p.black },
  TSKeywordOperator = { fg = p.white, bg = p.black },
  TSKeywordReturn = { fg = p.white, bg = p.black },
  TSLabel = { fg = p.white, bg = p.black },
  TSMethod = { fg = p.white, bg = p.black },
  TSNamespace = { fg = p.white, bg = p.black },
  TSNone = { fg = p.white, bg = p.black },
  TSNumber = { fg = p.white, bg = p.black },
  TSOperator = { fg = p.white, bg = p.black },
  TSParameter = { fg = p.white, bg = p.black },
  TSParameterReference = { fg = p.white, bg = p.black },
  TSProperty = { fg = p.white, bg = p.black },
  TSPunctDelimiter = { fg = p.white, bg = p.black },
  TSPunctBracket = { fg = p.white, bg = p.black },
  TSPunctSpecial = { fg = p.white, bg = p.black },
  TSRepeat = { fg = p.white, bg = p.black },
  TSString = { fg = p.white, bg = p.black },
  TSStringRegex = { fg = p.white, bg = p.black },
  TSStringEscape = { fg = p.white, bg = p.black },
  TSStringSpecial = { fg = p.white, bg = p.black },
  TSSymbol = { fg = p.white, bg = p.black },
  TSTag = { fg = p.white, bg = p.black },
  TSTagAttribute = { fg = p.white, bg = p.black },
  TSTagDelimiter = { fg = p.white, bg = p.black },
  TSText = { fg = p.white, bg = p.black },
  TSStrong = { fg = p.white, bg = p.black },
  TSEmphasis = { fg = p.white, bg = p.black },
  TSUnderline = { fg = p.white, bg = p.black },
  TSStrike = { fg = p.white, bg = p.black },
  TSTitle = { fg = p.white, bg = p.black },
  TSLiteral = { fg = p.white, bg = p.black },
  TSURI = { fg = p.white, bg = p.black },
  TSMath = { fg = p.white, bg = p.black },
  TSTextReference = { fg = p.white, bg = p.black },
  TSEnvironment = { fg = p.white, bg = p.black },
  TSEnvironmentName = { fg = p.white, bg = p.black },
  TSNote = { fg = p.white, bg = p.black },
  TSWarning = { fg = p.white, bg = p.black },
  TSDanger = { fg = p.white, bg = p.black },
  TSType = { fg = p.white, bg = p.black },
  TSTypeBuiltin = { fg = p.white, bg = p.black },
  TSVariable = { fg = p.white, bg = p.black },
  TSVariableBuiltin = { fg = p.white, bg = p.black },

  DiagnosticError = { fg = p.white, bg = p.black },
  DiagnosticWarn = { fg = p.white, bg = p.black },
  DiagnosticInfo = { fg = p.white, bg = p.black },
  DiagnosticHint = { fg = p.white, bg = p.black },

  LspReferenceText = { fg = p.white, bg = p.black },
  LspReferenceRead = { fg = p.white, bg = p.black },
  LspReferenceWrite = { fg = p.white, bg = p.black },

  CmpItemAbbr = { fg = p.white, bg = p.black },
  CmpItemAbbrDeprecated = { fg = p.white, bg = p.black },
  CmpItemAbbrMatch = { fg = p.white, bg = p.black },
  CmpItemAbbrMatchFuzzy = { fg = p.white, bg = p.black },
  CmpItemKind = { fg = p.white, bg = p.black },
  CmpItemMenu = { fg = p.white, bg = p.black },

  CryolineNormal = { fg = p.white, bg = p.black },
  CryolineVisual = { fg = p.white, bg = p.black },
  CryolineSelect = { fg = p.white, bg = p.black },
  CryolineInsert = { fg = p.white, bg = p.black },
  CryolineReplace = { fg = p.white, bg = p.black },
  CryolineElse = { fg = p.white, bg = p.black },

  DrexDir = { fg = p.white, bg = p.black },
  DrexLink = { fg = p.white, bg = p.black },
  DrexOthers = { fg = p.white, bg = p.black },
  DrexMarked = { fg = p.white, bg = p.black },
  DrexSelected = { fg = p.white, bg = p.black },
}

-- apply the colorscheme
apply_highlights(highlight_groups_table)
